Rails.application.routes.draw do

  get 'welcome/profile'
  get '/user/notifications' => 'users#notifications'
  get '/user/support' => 'users#support'
  get '/user/profile' => 'users#profile'
  get '/user/plan' => 'users#plan'
  get '/user/billing' => 'users#billing'
  get '/user' => 'users#profile'
  get 'home/index' 
  get 'welcome/dashboard'
  get 'welcome/index'

  get 'maths' => 'quizs#maths'
   	get 'maths/year7' => 'quizs#year7'
  		get 'year7/geometry' => 'quizs#geometry'
  		get 'year7/numberandalgebra' => 'quizs#numberandalgebra'
				get 'numberandalgebra/indexpowers' => 'quizs#indexpowers'
				get 'numberandalgebra/primenumbers1' => 'quizs#primenumbers1'
        get 'numberandalgebra/primefactors1' => 'quizs#primefactors1'
      get 'year7/statisticsandprobability' => 'quizs#statisticsandprobability'
		get 'maths/year8' => 'quizs#year8'
			get 'year8/numberalgebra' => 'quizs#numberalgebra'
        get 'numberalgebra/rationalnumbers' => 'quizs#rationalnumbers'
    get 'maths/year9' => 'quizs#year9'

	
  get 'science' => 'quizs#science'
    get 'science/chemistry' => 'quizs#chemistry'
  	get 'science/physics' => 'quizs#physics'
  		get 'physics/sound' => 'quizs#sound'
		get 'science/earthscience' => 'quizs#earthscience'
			get 'earthscience/tectonicplates' => 'quizs#tectonicplates'
	
  get 'english' => 'quizs#english'
  	get 'english/year7english' => 'quizs#year7english'
			get 'year7english/punctuation' => 'quizs#punctuation'
        get 'punctuation/basicpunctuation' => 'quizs#basicpunctuation'
        get 'punctuation/semicolon' => 'quizs#semicolon'
        get 'punctuation/grammar' => 'quizs#grammar'
        get 'punctuation/languagedevices' => 'quizs#languagedevices'
        get 'punctuation/writing' => 'quizs#writing'
        get 'punctuation/reading' => 'quizs#reading'
    get 'english/year8english' => 'quizs#year8english'
    get 'english/year9english' => 'quizs#year9english'
	
  get 'hass' => 'quizs#hass' #hass/geography/environmentalresources
    get 'hass/year9hass' => 'quizs#year9hass'
    get 'hass/year8hass' => 'quizs#year8hass'
    get 'hass/year7hass' => 'quizs#year7hass'
      get 'year7hass/history' => 'quizs#history'
      get 'year7hass/economics' => 'quizs#economics'
			get 'year7hass/geography' => 'quizs#geography'
				get 'geography/environmentalresources' => 'quizs#environmentalresources'
			get 'year7hass/civics' => 'quizs#civics'
				get 'civics/governmentanddemocracy' => 'quizs#governmentanddemocracy'

  get 'jqueryui' => 'quizs#jquery'
  get 'result' => 'quizs#result'
  post 'mark' => 'quizs#mark'
  get '/welcome/score' => 'quizs#show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end
